# Set prefix to Ctrl+b (default)
unbind C-a
set-option -g prefix C-b
bind-key C-b send-prefix

# Reload config with prefix + r
bind r source-file ~/.tmux.conf \; display "Config reloaded!"

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-battery'
set -g @plugin 'tmux-plugins/tmux-cpu'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'christoomey/vim-tmux-navigator'

# Continuously save the session
set -g @continuum-restore 'on'
set -g @continuum-save-interval '15'

# Tokyo Night theme colors with shorter names
set -g @tn-bg '#1a1b26'
set -g @tn-fg '#c0caf5'
set -g @tn-fg-darker '#565f89'
set -g @tn-yellow '#e0af68'
set -g @tn-green '#9ece6a'
set -g @tn-cyan '#7dcfff'
set -g @tn-blue '#7aa2f7'
set -g @tn-magenta '#bb9af7'
set -g @tn-red '#f7768e'

# Set status bar options using defined colors
set-option -g status-bg '#1a1b26'
set-option -g status-fg '#c0caf5'
set-option -g status-interval 5

# Left side of the status bar
set-option -g status-left "#[fg=$@tn-blue,bg=$@tn-bg] #S #[fg=$@tn-fg,bg=$@tn-bg]"

# Right side of the status bar
set-option -g status-right "#[fg=$@tn-fg,bg=$@tn-bg]%H:%M #[fg=$@tn-blue,bg=$@tn-bg]#[fg=$@tn-fg,bg=$@tn-blue]Battery: #{battery_percentage}#[fg=$@tn-bg,bg=$@tn-blue]#[fg=$@tn-fg,bg=$@tn-bg]"

# Center the active window title
# set-window-option -g window-status-current-format "#[fg=$@tn-bg,bg=$@tn-blue]#[fg=$@tn-bg,bg=$@tn-blue] #I:#W #[fg=$@tn-blue,bg=$@tn-bg]"
# set-window-option -g window-status-format "#[fg=$@tn-fg,bg=$@tn-bg] #I:#W "
# Center the active window title
set-window-option -g window-status-current-format "#[fg=#1a1b26,bg=#7aa2f7]#[fg=$@tn-bg,bg=#7aa2f7] #I:#W#F #[fg=#7aa2f7,bg=#1a1b26]"
set-window-option -g window-status-format "#[fg=#c0caf5,bg=#1a1b26] #I:#W "

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'

